"""Airflow DAG builder for Doris-native materialize/transform/metric SQL."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class DorisSqlDagBundle:
    dag_id: str
    dag_filename: str
    dag_source: str
    spec_filename: str
    spec: dict[str, Any]


def _safe(value: str) -> str:
    return "".join(c if c.isalnum() or c in "_-" else "_" for c in value)


def build_doris_sql_dag(
    *,
    artifact_id: str,
    kind: str,
    conn_id: str,
    precheck_sql: list[str] | None = None,
    setup_sql: list[str] | None = None,
    execute_sql: list[str],
    quality_sql: list[str] | None = None,
    publish_sql: list[str] | None = None,
    schedule: str | None = None,
) -> DorisSqlDagBundle:
    """Build a deterministic SQL-only DAG with sidecar JSON statements."""
    short = _safe(artifact_id.replace("-", "")[:12] or "manual")
    dag_id = f"ontometa_doris_{kind}_{short}"
    spec = {
        "dag_id": dag_id,
        "kind": kind,
        "conn_id": conn_id,
        "schedule": schedule or None,
        "precheck_sql": list(precheck_sql or ["SELECT 1"]),
        "setup_sql": list(setup_sql or []),
        "execute_sql": list(execute_sql),
        "quality_sql": list(quality_sql or ["SELECT 1"]),
        "publish_sql": list(publish_sql or []),
    }
    filename = f"{dag_id}.json"
    source = _TEMPLATE.replace("@@DAG_ID@@", dag_id).replace("@@SPEC_FILENAME@@", filename)
    return DorisSqlDagBundle(
        dag_id=dag_id,
        dag_filename=f"{dag_id}.py",
        dag_source=source,
        spec_filename=filename,
        spec=spec,
    )


_TEMPLATE = '''\
# Doris SQL DAG: @@DAG_ID@@
# Generated by ontoMeta. SQL lives in the JSON sidecar.
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator, SQLCheckOperator
from datetime import datetime, timedelta
import json
from pathlib import Path

_SPEC_PATH = Path(__file__).parent / "@@SPEC_FILENAME@@"
_SPEC = json.loads(_SPEC_PATH.read_text(encoding="utf-8"))

def _read_spec():
    return {"spec_path": str(_SPEC_PATH), "kind": _SPEC["kind"]}

with DAG(
    dag_id="@@DAG_ID@@",
    schedule=_SPEC.get("schedule"),
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_runs=1,
    default_args={
        "owner": "ontoMeta",
        "retries": 1,
        "retry_delay": timedelta(minutes=5),
        "email_on_failure": False,
    },
    tags=["ontometa", "doris", _SPEC["kind"]],
) as dag:
    read_spec = PythonOperator(task_id="read_spec", python_callable=_read_spec)
    precheck = SQLExecuteQueryOperator(
        task_id="precheck", conn_id=_SPEC["conn_id"],
        sql=_SPEC["precheck_sql"], split_statements=True,
    )
    read_spec >> precheck
    previous = precheck
    if _SPEC.get("setup_sql"):
        setup = SQLExecuteQueryOperator(
            task_id="setup", conn_id=_SPEC["conn_id"],
            sql=_SPEC["setup_sql"], split_statements=True,
        )
        previous >> setup
        previous = setup
    execute = SQLExecuteQueryOperator(
        task_id="execute_doris_sql", conn_id=_SPEC["conn_id"],
        sql=_SPEC["execute_sql"], split_statements=True,
    )
    previous >> execute
    quality = SQLCheckOperator(
        task_id="quality_check", conn_id=_SPEC["conn_id"],
        sql=_SPEC["quality_sql"][0],
    )
    execute >> quality
    if _SPEC.get("publish_sql"):
        publish = SQLExecuteQueryOperator(
            task_id="publish", conn_id=_SPEC["conn_id"],
            sql=_SPEC["publish_sql"], split_statements=True,
        )
        quality >> publish
'''
