"""baseline_schema

Revision ID: 5a881e5c0024
Revises: 
Create Date: 2026-07-17 14:06:09.780225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a881e5c0024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_logic_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_logic_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_logic_categories_name'), ['name'], unique=True)

    op.create_table('datahub_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gms_url', sa.String(length=512), nullable=False),
    sa.Column('frontend_url', sa.String(length=512), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=True),
    sa.Column('use_mock', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('datahub_domain_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_contexts_datahub_domain_id'), ['datahub_domain_id'], unique=True)

    op.create_table('entity_change_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_change_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_change_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('external_apps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_key', sa.String(length=64), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_apps_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_apps_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_apps_api_key_prefix'), ['api_key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_apps_app_key'), ['app_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_apps_status'), ['status'], unique=False)

    op.create_table('llm_service_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('use_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_version_records_entity_id'), ['entity_id'], unique=False)

    op.create_table('chat_bi_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_bi_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_bi_conversations_domain_id'), ['domain_id'], unique=False)

    op.create_table('ontologies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_context_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_context_id'], ['domain_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ontologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ontologies_domain_context_id'), ['domain_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ontologies_status'), ['status'], unique=False)

    op.create_table('business_logics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('logic_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression_summary', sa.Text(), nullable=True),
    sa.Column('expression_draft', sa.Text(), nullable=True),
    sa.Column('expression_json', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_logic_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_logics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_logics_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_logics_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_logics_status'), ['status'], unique=False)

    op.create_table('change_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('confirmation_status', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_confirmations_confirmation_status'), ['confirmation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_confirmations_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_confirmations_target_id'), ['target_id'], unique=False)

    op.create_table('chat_bi_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_bi_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_bi_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_bi_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('draft_evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_evidences_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_evidences_source_ref'), ['source_ref'], unique=False)

    op.create_table('draft_generation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_context_id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_context_id'], ['domain_contexts.id'], ),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_generation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_generation_tasks_domain_context_id'), ['domain_context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_generation_tasks_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_generation_tasks_status'), ['status'], unique=False)

    op.create_table('object_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_term_id', sa.String(length=255), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_types_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_types_source_ref'), ['source_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_types_status'), ['status'], unique=False)

    op.create_table('business_logic_object_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_logic_id', sa.String(length=36), nullable=False),
    sa.Column('object_type_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_logic_id'], ['business_logics.id'], ),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_logic_id', 'object_type_id', 'role', name='uq_logic_object_role')
    )
    with op.batch_alter_table('business_logic_object_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_logic_object_bindings_business_logic_id'), ['business_logic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_logic_object_bindings_object_type_id'), ['object_type_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('source_field_ref', sa.String(length=512), nullable=True),
    sa.Column('semantic_type', sa.String(length=100), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_object_type_id'), ['object_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)

    op.create_table('relation_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_object_type_id', sa.String(length=36), nullable=False),
    sa.Column('target_object_type_id', sa.String(length=36), nullable=False),
    sa.Column('cardinality', sa.String(length=50), nullable=True),
    sa.Column('structure_type', sa.String(length=50), nullable=True),
    sa.Column('mapping_object_type_id', sa.String(length=36), nullable=True),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_object_type_id'], ['object_types.id'], ),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ),
    sa.ForeignKeyConstraint(['source_object_type_id'], ['object_types.id'], ),
    sa.ForeignKeyConstraint(['target_object_type_id'], ['object_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relation_types_mapping_object_type_id'), ['mapping_object_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_types_ontology_id'), ['ontology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_types_source_object_type_id'), ['source_object_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_types_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_relation_types_target_object_type_id'), ['target_object_type_id'], unique=False)

    op.create_table('business_logic_property_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_logic_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_logic_id'], ['business_logics.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_logic_id', 'property_id', 'role', name='uq_logic_property_role')
    )
    with op.batch_alter_table('business_logic_property_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_logic_property_bindings_business_logic_id'), ['business_logic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_logic_property_bindings_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_logic_property_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_logic_property_bindings_property_id'))
        batch_op.drop_index(batch_op.f('ix_business_logic_property_bindings_business_logic_id'))

    op.drop_table('business_logic_property_bindings')
    with op.batch_alter_table('relation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relation_types_target_object_type_id'))
        batch_op.drop_index(batch_op.f('ix_relation_types_status'))
        batch_op.drop_index(batch_op.f('ix_relation_types_source_object_type_id'))
        batch_op.drop_index(batch_op.f('ix_relation_types_ontology_id'))
        batch_op.drop_index(batch_op.f('ix_relation_types_mapping_object_type_id'))

    op.drop_table('relation_types')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_status'))
        batch_op.drop_index(batch_op.f('ix_properties_object_type_id'))

    op.drop_table('properties')
    with op.batch_alter_table('business_logic_object_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_logic_object_bindings_object_type_id'))
        batch_op.drop_index(batch_op.f('ix_business_logic_object_bindings_business_logic_id'))

    op.drop_table('business_logic_object_bindings')
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_types_status'))
        batch_op.drop_index(batch_op.f('ix_object_types_source_ref'))
        batch_op.drop_index(batch_op.f('ix_object_types_ontology_id'))

    op.drop_table('object_types')
    with op.batch_alter_table('draft_generation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_generation_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_draft_generation_tasks_ontology_id'))
        batch_op.drop_index(batch_op.f('ix_draft_generation_tasks_domain_context_id'))

    op.drop_table('draft_generation_tasks')
    with op.batch_alter_table('draft_evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_evidences_source_ref'))
        batch_op.drop_index(batch_op.f('ix_draft_evidences_ontology_id'))

    op.drop_table('draft_evidences')
    with op.batch_alter_table('chat_bi_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_bi_messages_conversation_id'))

    op.drop_table('chat_bi_messages')
    with op.batch_alter_table('change_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_confirmations_target_id'))
        batch_op.drop_index(batch_op.f('ix_change_confirmations_ontology_id'))
        batch_op.drop_index(batch_op.f('ix_change_confirmations_confirmation_status'))

    op.drop_table('change_confirmations')
    with op.batch_alter_table('business_logics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_logics_status'))
        batch_op.drop_index(batch_op.f('ix_business_logics_ontology_id'))
        batch_op.drop_index(batch_op.f('ix_business_logics_category_id'))

    op.drop_table('business_logics')
    with op.batch_alter_table('ontologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ontologies_status'))
        batch_op.drop_index(batch_op.f('ix_ontologies_domain_context_id'))

    op.drop_table('ontologies')
    with op.batch_alter_table('chat_bi_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_bi_conversations_domain_id'))

    op.drop_table('chat_bi_conversations')
    with op.batch_alter_table('version_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_records_entity_id'))
        batch_op.drop_index(batch_op.f('ix_version_records_created_at'))

    op.drop_table('version_records')
    op.drop_table('llm_service_configs')
    with op.batch_alter_table('external_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_apps_status'))
        batch_op.drop_index(batch_op.f('ix_external_apps_app_key'))
        batch_op.drop_index(batch_op.f('ix_external_apps_api_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_external_apps_api_key_hash'))
        batch_op.drop_index(batch_op.f('ix_external_apps_api_key'))

    op.drop_table('external_apps')
    with op.batch_alter_table('entity_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_change_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_change_logs_created_at'))

    op.drop_table('entity_change_logs')
    with op.batch_alter_table('domain_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_contexts_datahub_domain_id'))

    op.drop_table('domain_contexts')
    op.drop_table('datahub_settings')
    with op.batch_alter_table('business_logic_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_logic_categories_name'))

    op.drop_table('business_logic_categories')
    # ### end Alembic commands ###
